INSERT INTO LDCODE (CODETYPE, CODE, CODENAME, CODEALIAS, COMCODE, OTHERSIGN) VALUES ('riskType', '1', '低风险', null, null, null);
INSERT INTO LDCODE (CODETYPE, CODE, CODENAME, CODEALIAS, COMCODE, OTHERSIGN) VALUES ('riskType', '2', '低至中度风险', null, null, null);
INSERT INTO LDCODE (CODETYPE, CODE, CODENAME, CODEALIAS, COMCODE, OTHERSIGN) VALUES ('riskType', '3', '中度风险', null, null, null);
INSERT INTO LDCODE (CODETYPE, CODE, CODENAME, CODEALIAS, COMCODE, OTHERSIGN) VALUES ('riskType', '4', '中至高度风险', null, null, null);
INSERT INTO LDCODE (CODETYPE, CODE, CODENAME, CODEALIAS, COMCODE, OTHERSIGN) VALUES ('riskType', '5', '高度风险', null, null, null);